export const CONTACT_LIST = 'Contacts'
export const CONTACT_DETAILS = 'Contact Details'
export const CREATE_CONTACT = 'Create Contact'
export const SETTINGS = 'Settings'
export const LOGIN = 'LOGIN'
export const REGISTER = 'Sign Up'
export const LOGOUT = 'logout'